.PHONY: clean All

All:
	@echo "----------Building project:[ pila - Debug ]----------"
	@cd "pila" && $(MAKE) -f  "pila.mk"
clean:
	@echo "----------Cleaning project:[ pila - Debug ]----------"
	@cd "pila" && $(MAKE) -f  "pila.mk" clean
